import {StyleSheet} from 'react-native';

export const TodoStyle = StyleSheet.create({
    mainContainer: {
        marginHorizontal: 10,
        marginVertical: 10,
    },
    mainHeadingText: {
        fontSize: 25,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    textInput: {
        width: '90%',
        borderWidth: 1,
        alignSelf: 'center',
        marginVertical: 20,
        borderRadius: 5,
        borderColor: '#948e7e',
    },
    detailsContainer: {
        width: '90%',
        borderWidth: 1,
        alignSelf: 'center',
        padding: 10,
        borderRadius: 7,
        borderColor: '#948e7e',
        backgroundColor: '#6fb378',
        marginVertical: '2%',
    },
    detailsTextContainer: {
        fontSize: 15,
        marginVertical: 7,
        color: 'white',
        fontWeight: 'bold',
    },
    creatTodoBtn: {
        width: '90%',
        alignSelf: 'center',
        marginBottom: 10,
        padding: 10,
        backgroundColor: '#6fb378',
        borderRadius: 7,
        borderColor: '#948e7e',
        shadowColor: 'black',
        elevation: 8,
    },
    creatTodoBtnText: {
        fontSize: 17,
        color: 'white',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    centerview: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)', // for overlay effect
    },
    modalview: {
        width: '80%',
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        elevation: 10,
    },
    modalInputField: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#948e7e',
        borderRadius: 5,
        padding: 10,
        marginBottom: 15,
    },
    delBtn:{
        backgroundColor:'red',
        width:'30%',
        paddingVertical:6,
        marginVertical: 10,
        borderRadius:5,
        shadowColor: 'red',
        elevation:5,
    },
    delBtnTxt:{
        textAlign:'center',
        color:'white',
        fontSize:15,
        fontWeight:'bold',
    },
    cancelBtn:{
        backgroundColor: 'red',
        paddingVertical: 10,
        borderRadius: 5,
        shadowColor: 'black',
        elevation: 5,
        width: '90%',
        margin: 'auto',
    },
});
